version: "3"

services:
  operator:
    image: gcr.io/openoracle-de73b/operator-test:latest
    volumes:
      - ../../:/open-oracle/
    working_dir: /open-oracle
    env_file:
      - .env
    command: --config ./static-configs/holesky_test/operator-docker-compose.yaml update-operator-bls-key-and-signer
