version: "3"

services:
  operator:
    image: gcr.io/openoracle-de73b/operator-test:latest
    volumes:
      - ../../:/open-oracle/
    working_dir: /open-oracle
    env_file:
      - .env
    command: --config ./static-configs/plumetest/operator-docker-compose.yaml start-operator
    ports:
      - 9091:9091
    networks:
      - openoracle-operator

networks:
  openoracle-operator:
    name: openoracle-operator