version: "3"

services:
  operator:
    image: gcr.io/openoracle-de73b/operator-js:latest
    volumes:
      - ../../static-configs:/open-oracle/static-configs
      - ../../keys:/open-oracle/keys
    working_dir: /open-oracle
    env_file:
      - .env
    command: --config ./static-configs/mainnet/operator-docker-compose.yaml start-operator
    ports:
      - 9091:9091
    networks:
      - openoracle-operator

networks:
  openoracle-operator:
    name: openoracle-operator