version: "3"

services:
  operator:
    image: gcr.io/openoracle-de73b/operator:latest
    volumes:
      - ../../:/open-oracle/
    working_dir: /open-oracle
    environment:
      OPERATOR_ADDRESS: "<Operator address that matches with your ECDSA key>"
      BLS_PRIVATE_KEY_PATH: "keys/bls_key/keys/1.bls.key.json"
      OPERATOR_BLS_KEY_PASSWORD: "<Passworkd to your BLS key>"
      ECDSA_PRIVATE_KEY_PATH: "keys/ecdsa_key/keys/1.ecdsa.key.json"
      OPERATOR_ECDSA_KEY_PASSWORD: "<Password to your ECDSA key>"
      HTTP_RPC_URL: "<HTTP RPC Url for Holesky>"
      WS_RPC_URL: "<Websocket RPC Url for Holesky>"
    command: --config ./static-configs/holesky/operator-docker-compose.yaml
