version: "3"

services:
  operator:
    image: gcr.io/openoracle-de73b/operator-js-holesky:latest
    volumes:
      - ../../static-configs:/open-oracle/static-configs
      - ../../keys:/open-oracle/keys
    working_dir: /open-oracle
    env_file:
      - .env
    command: --config ./static-configs/holesky/operator-docker-compose.yaml update-operator-bls-key-and-signer
