{
 "title": "Avs Oracle",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "New Tasks Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "openoracle_num_tasks_received", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Signed Tasks Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "openoracle_num_signed_task_responses_accepted_by_aggregator",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Performance Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "eigen_performance_score{avs_name=\"avs-oracle\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Sent To CNBC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "openoracle_num_request_sent_to_cnbc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Sent To Nasdaq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "openoracle_num_request_sent_to_nasdaq",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Received From CNBC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "openoracle_num_error_received_from_cnbc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Received From Nasdaq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "openoracle_num_error_received_from_cnbc",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}