global:
  scrape_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["operator:9091"]

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      # host.docker.internal might not work on linux
      # TODO: do https://stackoverflow.com/a/67158212/4971151
      # - targets: ["host.docker.internal:9090"]
      - targets: ["host.docker.internal:9090"]
        labels:
          bot: "avs-orcl-node"
    relabel_configs:
      # is this actually useful? We already have the job name
