# this sets the logger level (true = info, false = debug)
production: false

# EigenLayer Slasher contract address

# This is the address of the slasher which is deployed in the anvil saved state
# The saved eigenlayer state is located in tests/anvil/eigenlayer-deployed-anvil-state.json
avs_registry_coordinator_address: 0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690
operator_state_retriever_address: 0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8

# ETH RPC URL
eth_rpc_url: http://host.docker.internal:8545
eth_ws_url: ws://host.docker.internal:8545

# address which the aggregator listens on for operator signed messages
aggregator_server_ip_port_address: open-oracle-aggregator:8090

# avs node spec compliance https://eigen.nethermind.io/docs/spec/intro
eigen_metrics_ip_port_address: 0.0.0.0:9090
enable_metrics: true
node_api_ip_port_address: 0.0.0.0:9010
enable_node_api: true

# we need to register the operator on startup when running the docker compose file
# because unfortunately we cannot register the operator previously and save it in the anvil json file
# This is because anvil only dumps the state, and not the receipt tree, so when we restart anvil with
# the registered operator, it's blspubkey registering event with the compendium is not present anymore,
# and so the aggregator can't find it.... very annoying
register_operator_on_startup: true
# address of token to deposit tokens into when registering on startup
# addresses.erc20MockStrategy in tests/anvil/credible_squaring_avs_deployment_output.json
token_strategy_addr: 0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f